### PR TITLE
Feature: backend sources 

### PR DESCRIPTION
**Pull request by lochiiconnectivity**
(Submitted at the request of Lasse) 

This incorporates our patch for backend sources in the core. 

To save polluting the notes in the pull request, I've put up more information about this patch here:

http://www.convergence.cx/backend_source.txt

### CODE REVIEW

**Comment by lochiiconnectivity** [comment]
Added VTC v00045 to this pull in response to the discussion on IRC today.

**Comment by bsdphk** [comment]
I have cherry-picked the varnishtest bits, since they're sort of unrelated to the rest.

The test-case doesn't work on FreeBSD, and I presume won't work on anything except maybe Linux.  (Please always at least "expect resp.status == 200" so 503's don't slip through).

Stylistically there are a number of source lines that become too long and needs to be wrapped.

In general the "verbosity" of this patch bothers me in a number of ways, an also the fact that it isn't very general.

Another more general way to attack this particular problem would be to invent a "from to" syntax for addresses.  Random idea:

    .host = "192.168.1.0:80/172.16.1.2";

Meaning "connect to 192.168.1.0 port 80, using source address 172.16.1.2"

For that to become really "neat", we would have to double the size of struct suckaddr, so that it contains both source and optional destination.

The advantage of this approach is that it would kick in everywhere:  varnishadm's -T argument, varnishd's -M argument, backends in VCL etc.

The downside is doubling the size of suckaddrs.

One could further extend the syntax:

    "192.168.1.2/fxp0"

Meaning: use IP# from interface "fxp0"

But then we get seriously into second-guessing the kernel.

I'll have to ponder this some more...

**Comment by lochiiconnectivity** [comment]
Modified the VTC to test only the code path, as there isn't a good OS independent way of testing true sourcing for now. changed VTC to use the new remote IP syntax (remote.ip) from cherrypick.

**Comment by lochiiconnectivity** [comment]
wrapped some lines at phk's request.

**Comment by bsdphk** [comment]
I'm nixing this one for now.

If we want to do something like this, it should be along the lines of generality, but this patch is not it.

**Pull request closed without merging**
